# essential libraries
library(knitr)
suppressPackageStartupMessages(library(kableExtra))
suppressPackageStartupMessages(library(car))
suppressPackageStartupMessages(library(dunn.test))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(broom))
suppressPackageStartupMessages(library(patchwork))
suppressPackageStartupMessages(library(ggResidpanel))
library(pwr)
library(powerAnalysis)
