# essential libraries
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(broom))
suppressPackageStartupMessages(library(corrr))
suppressPackageStartupMessages(library(tidymodels))
suppressPackageStartupMessages(library(tidytext))
suppressPackageStartupMessages(library(palmerpenguins))
suppressPackageStartupMessages(library(ggdendro))
suppressPackageStartupMessages(library(patchwork))
suppressPackageStartupMessages(library(reticulate))
theme_set(theme_bw())
scale_colour_discrete <- function(...) scale_colour_brewer(palette = "Dark2")
scale_fill_discrete <- function(...) scale_fill_brewer(palette = "Dark2")
